[Unit]
After=NetworkManager.service ModemManager.service
[Service]
ExecStart=
ExecStart=/usr/local/libexec/aag-power-transaction /usr/local/libexec/aag-sleep-transaction boot-reconcile
TimeoutStartSec=180s
