[Unit]
OnSuccess=
OnSuccess=aag-hibernate-transaction-finish.service
OnFailure=
OnFailure=aag-hibernate-transaction-finish.service
[Service]
ExecStartPre=
ExecStartPre=/usr/local/libexec/aag-power-transaction hibernate-native-pre
ExecStopPost=
ExecStopPost=/usr/local/libexec/aag-power-transaction hibernate-native-post
TimeoutStopSec=30s
