[Service]
ExecStartPre=
ExecStartPre=/usr/local/libexec/aag-power-transaction /usr/local/libexec/aag-sleep-transaction begin
ExecStartPost=
ExecStartPost=/usr/local/libexec/aag-power-transaction /usr/local/libexec/aag-sleep-transaction verify-release
ExecStopPost=
ExecStopPost=/usr/local/libexec/aag-power-transaction /usr/local/libexec/aag-sleep-transaction v2-teardown
